// Service Worker policy. Each Pages build appends its commit revision to the
// cache base name, so a new deployment automatically receives a fresh runtime
// cache and activate() can remove caches from older deployments.
self.TOUKEI_SW_CONFIG = Object.freeze({
  cachePrefix: 'toukei-grade1-',
  cacheName: 'toukei-grade1-runtime',

  // Online requests should see the latest published content. service-worker.js
  // short-circuits these strategies to Cache Storage when WorkerNavigator says
  // the browser is offline, so Wi-Fi-off navigation does not wait for a failed
  // request before rendering the saved教材.
  defaultStrategy: 'network-first',
  strategyByKind: Object.freeze({
    navigation: 'network-first',
    sameOrigin: 'network-first',
    // These URLs are version-pinned, so cache-first avoids unnecessary CDN
    // traffic without risking stale runtime code.
    externalAsset: 'cache-first',
  }),

  // Keep the shell and a same-origin KaTeX fallback available after the first
  // online visit. The local KaTeX CSS pulls its font dependencies into the
  // cache during Service Worker install, so formulas do not depend on CDN
  // availability in airplane mode.
  appShell: Object.freeze([
    './index.html',
    './home.md',
    './_sidebar.md',
    './math-renderer.js',
    './site-meta.json',
    './vendor/katex/katex.min.css',
    './vendor/katex/katex.min.js',
  ]),

  // Docsify remains CDN-backed for normal online loading. Manual full-site
  // caching stores these assets as well; KaTeX itself has a local fallback
  // above so math rendering does not rely on the external host offline.
  externalAssets: Object.freeze([
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/themes/vue.css',
    'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css',
    'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js',
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/docsify.min.js',
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/plugins/search.min.js',
  ]),
  cacheExternalHosts: Object.freeze(['cdn.jsdelivr.net']),

  navigationFallback: './index.html',
  siteMetaUrl: './site-meta.json',

  // Set this to true if we later want a full-site offline snapshot instead of
  // caching pages on demand. The manifest is generated by the Pages workflow.
  warmPublishedFiles: false,
  publishedFilesManifest: './pages-manifest.txt',

  // Manual full-site caching uses bounded concurrency to avoid flooding the
  // browser/network while still finishing in a reasonable time.
  manualCacheConcurrency: 6,
});
