// Service Worker policy. Normal content updates do not require a cache-version bump:
// network-first refreshes cached responses whenever the network is available.
// Change only the strategy values below to switch policy later.
self.TOUKEI_SW_CONFIG = Object.freeze({
  cachePrefix: 'toukei-grade1-',
  cacheName: 'toukei-grade1-runtime-v1',

  defaultStrategy: 'network-first',
  strategyByKind: Object.freeze({
    navigation: 'network-first',
    sameOrigin: 'network-first',
    externalAsset: 'network-first',
  }),

  // Keep the shell available after the first online visit. Markdown pages that
  // are actually opened are cached by the runtime strategy below.
  appShell: Object.freeze([
    './index.html',
    './home.md',
    './_sidebar.md',
    './math-renderer.js',
  ]),

  // These CDN files are required to render Docsify + KaTeX offline. CSS url()
  // dependencies (for example KaTeX fonts) are discovered and cached by the
  // worker automatically during install.
  externalAssets: Object.freeze([
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/themes/vue.css',
    'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css',
    'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js',
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/docsify.min.js',
    'https://cdn.jsdelivr.net/npm/docsify@4.13.1/lib/plugins/search.min.js',
  ]),
  cacheExternalHosts: Object.freeze(['cdn.jsdelivr.net']),

  navigationFallback: './index.html',

  // Set this to true if we later want a full-site offline snapshot instead of
  // caching pages on demand. The manifest is generated by the Pages workflow.
  warmPublishedFiles: false,
  publishedFilesManifest: './pages-manifest.txt',
});
